factList = [
    'Yuma, Arizona gets over 4000 hours of sunshine a year, making it the sunniest place on earth. The least sunny place is the South Pole, where the sun only shines on 182 days a year.',
    'Rain contains vitamin B12. ',
    'A bolt of lightning is five times hotter than the sun. ',
    'A hurricane releases enough energy in one second to equal that of 10 atomic bombs. ',
    'There are 2,000 thunderstorms on Earth every minute.',
    'There are ice caves in Iceland that have hot springs.',
    'The fastest recorded raindrop was 18 mph!',
    'The wind is silent until it blows against something. ',
    'The US gets over 1200 tornadoes a year.',
    'Lightning can, in fact, strike twice.',
    'The moon is very hot (224 degrees Fahrenheit, average) during the day but very cold (-243 degrees average) at night.',
    'Venus spins clockwise. It’s the only planet that does!',
    'One teaspoon of a neutron star would weigh six-billion tons.',
    'Sally Ride was the first American woman to fly in space, on June 18, 1983.',
    'The tallest tree in the world is a Sequoia redwood, that stands over 379 feet tall. ',
    'There are more than 391,000 known plant species in the world. ',
    'One million Earths could fit inside the sun!',
    'Even in an airplane, a trip to Pluto would take about 800 years. ',
    'Neptune’s days are 16 hours long.',
    'It takes eight minutes and 19 seconds for light to travel from the sun to Earth.',
    'Jupiter is the fastest spinning planet in the solar system (it only takes about 10 hours to complete a full rotation on its axis). ',
    'Not only does everyone have unique fingerprints, humans also have unique tongue-prints!',
    'The average brain weighs about three pounds. A newborn brain weight about 3/4 of a pound. ',
    'Your nose and ears never stop growing. ',
    'The footprints on the moon will be there for 100 million years. ',
    'The Earth\'s core is as hot as the surface of the sun. ',
    'Europa, on of Jupiter\'s moons, has saltwater geyers that are 20x taller than Mt. Everest. ',
    'The very first animals in space were fruit flies...they were sent up in 1947 and recovered alive. ',
    'Saturn\'s rings are made from trillions of chunks of orbiting ice.',
    'Did you know eating cheese at the end of a meal can help neutralise the acids in your mouth and reduce the chance of tooth decay.',
    'An adult brain weighs three pounds.', 'The brain cannot feel pain.',
    'Did you know that the chance of your fingerprint being the same as someone else’s fingerprint is 1 in 64 billion?',
    'Polar bears have no natural enemies.',
    'Polar bears actually have black skin!',
    'The smallest lightest bone of the human skeleton is the stapes found in the middle ear.',
    'Did you know the smallest bone in the body is the stirrup, deep inside the ear, which is about the size of a grain of rice.',
    '1 millions Earths could fit inside the Sun!',
    'The Sun is a colossal ball of helium and hydrogen gas and is the heaviest body in our Solar System.',
    'The immensely strong gravity of the Sun keeps objects in the solar system orbiting around it.'
]
